[tool.poetry]
name = "py_arcade"
version = "0.1.0"
description = ""
authors = ["Casadina <casadina@tuta.io>"]

[tool.poetry.dependencies]
python = "^3.9"
arcade = "^2.6.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
